// various constants related to nbr, position, etc. of cubes
extern DPOINT3D SMALLCUBEOFFSET;
extern DPOINT3D SMALLCUBEVIEWPOINT;
extern DPOINT3D LARGECUBEOFFSET;
extern DPOINT3D LARGECUBEVIEWPOINT;
extern DPOINT3D SmallCubeBaseRectP1;
extern DPOINT3D SmallCubeBaseRectP2;
extern double SmallCubeHeight;
extern DPOINT3D LargeCubeBaseRectP1;
extern DPOINT3D LargeCubeBaseRectP2;
extern double LargeCubeHeight;


